services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./langfuse/.env
      
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  langflow:
    build:
      context: ./langflow
      dockerfile: Dockerfile
    depends_on:
      - langfuse-server
    ports:
      - "7860:7860"
    env_file: 
      - ./langflow/.env
    command: langflow run --host 0.0.0.0 --port 7860

volumes:
  database_data:
    driver: local